services:
  green-app:
    image: myapp:v1
    container_name: green-app
    environment:
      - VERSION=GREEN
    ports:
      - "3003:3000"
    networks:
      - devops-net

networks:
  devops-net:
    external: true
