services:
  green-app:
    image: ${IMAGE_NAME}:${TAG}
    container_name: green-app
    environment:
      - APP_VERSION=GREEN
    ports:
      - "3003:3000"
    networks:
      - devops-net

networks:
  devops-net:
    external: true
