version: '3'

services:
  blue-app:
    image: ${IMAGE_NAME}:${TAG}
    container_name: blue-app
    environment:
      - APP_VERSION=BLUE
    ports:
      - "3002:3000"
    networks:
      - devops-net

networks:
  devops-net:
    external: true
